id: A14829274
base_file: f101E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:00:21.703428
  last_modified_at: 2022-05-30 22:00:21.703437
