id: A14829274
base_file: f7F33.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:00:21.707011
  last_modified_at: 2022-05-30 22:00:21.707017
